#!/usr/bin/env python3
"""Generate and seal an independent V5-C/ECRG calibration split.

The split is generated by frozen DCA_3, filtered only by scenario-level hard
requirements, and sampled without running a VDA or consulting model scores.
"""

from __future__ import annotations

import argparse
import json
import os
import random
import subprocess
import sys
from collections import Counter
from pathlib import Path
from typing import Any

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
for path in (ROOT, ROOT / "scripts"):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from agentguard_zero.training.coevolution import (
    LineageError,
    atomic_write_json,
    canonical_json,
    load_checkpoint_manifest,
    read_json,
    scenario_fingerprint,
    sha256_bytes,
    sha256_file,
    sha256_source_tree,
    utc_now,
)
from agentguard_zero.training.vda_dataset import scenario_to_training_row
from scripts.generate_final_heldout import (
    TASK_IDS,
    _iter_parquet_scenarios,
    _run_parallel,
    _task_id,
    build_exclusion_ledger,
    select_heldout,
    semantic_overlap_fingerprint,
)


def _extend_with_tmcd_test(
    ledger: dict[str, Any],
    *,
    test_path: Path,
    test_manifest_path: Path,
) -> dict[str, Any]:
    if not test_path.is_file() or not test_manifest_path.is_file():
        raise LineageError("sealed TMCD-Test is required before V5-C calibration")
    test_manifest = read_json(test_manifest_path)
    if test_manifest.get("status") != "sealed":
        raise LineageError("TMCD-Test manifest is not sealed")
    if int(test_manifest.get("source_dca_round", -1)) != 3:
        raise LineageError("TMCD-Test was not generated by DCA_3")
    if int(test_manifest.get("selected_count", -1)) != 2400:
        raise LineageError("TMCD-Test manifest does not seal 2,400 scenarios")
    if test_manifest.get("task_counts") != {
        "T1": 600,
        "T2": 600,
        "T3": 600,
        "T4": 600,
    }:
        raise LineageError("TMCD-Test manifest is not balanced across T1--T4")
    if test_manifest.get("final_heldout_sha256") != sha256_file(test_path):
        raise LineageError("TMCD-Test parquet no longer matches its sealed manifest")

    lineage = set(ledger["lineage_fingerprints"])
    semantic = set(ledger["semantic_fingerprints"])
    before_lineage = len(lineage)
    before_semantic = len(semantic)
    rows = 0
    for scenario in _iter_parquet_scenarios(test_path):
        rows += 1
        lineage.add(scenario_fingerprint(scenario))
        semantic.add(semantic_overlap_fingerprint(scenario))
    if rows != 2400:
        raise LineageError(f"sealed TMCD-Test has {rows} rows, expected 2400")
    ledger = dict(ledger)
    sources = dict(ledger.get("sources", {}))
    sources["sealed_tmcd_test"] = {
        "path": str(test_path.resolve()),
        "sha256": sha256_file(test_path),
        "manifest": str(test_manifest_path.resolve()),
        "manifest_sha256": sha256_file(test_manifest_path),
        "rows": rows,
        "new_lineage_fingerprints": len(lineage) - before_lineage,
        "new_semantic_fingerprints": len(semantic) - before_semantic,
    }
    ledger.update(
        {
            "kind": "v5c_calibration_exclusion_ledger",
            "sources": sources,
            "sealed_tmcd_test_present": True,
            "lineage_fingerprint_count": len(lineage),
            "semantic_fingerprint_count": len(semantic),
            "lineage_fingerprints": sorted(lineage),
            "semantic_fingerprints": sorted(semantic),
        }
    )
    return ledger


def _candidate_command(
    *,
    root: Path,
    dca_manifest_path: Path,
    output: Path,
    num_candidates: int,
    batch_size: int,
    max_input_tokens: int,
    max_new_tokens: int,
    num_shards: int,
    shard_index: int,
    seed: int,
    task_id: str | None = None,
) -> list[str]:
    command = [
        sys.executable,
        str(root / "scripts" / "generate_dca_scenarios.py"),
        "--checkpoint-manifest",
        str(dca_manifest_path),
        "--output",
        str(output),
        "--num-candidates",
        str(num_candidates),
        "--batch-size",
        str(batch_size),
        "--max-input-tokens",
        str(max_input_tokens),
        "--max-new-tokens",
        str(max_new_tokens),
        "--num-shards",
        str(num_shards),
        "--shard-index",
        str(shard_index),
        "--seed",
        str(seed),
        "--experiment-variant",
        "full",
    ]
    if task_id:
        command.extend(("--task-id", task_id))
    return command


def _gpu_environment(
    *,
    gpu_id: str,
    backbone: str,
    namespace: str,
) -> dict[str, str]:
    environment = os.environ.copy()
    environment["CUDA_VISIBLE_DEVICES"] = gpu_id
    triton_cache = Path(
        os.environ.get("AGZ_TRITON_CACHE_ROOT", "/tmp/agentguard_zero_triton")
    ) / f"agz_{backbone}_v5c_calibration" / namespace
    triton_cache.mkdir(parents=True, exist_ok=True)
    environment["TRITON_CACHE_DIR"] = str(triton_cache)
    return environment


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=str(ROOT))
    parser.add_argument("--artifact-scope", default="tmcd_v242")
    parser.add_argument("--backbone", choices=["qwen3.5-4b"], required=True)
    parser.add_argument("--checkpoint-manifest")
    parser.add_argument("--candidate-count", type=int, default=1600)
    parser.add_argument("--per-task", type=int, default=200)
    parser.add_argument("--batch-size", type=int, default=72)
    parser.add_argument("--max-input-tokens", type=int, default=2048)
    parser.add_argument("--max-new-tokens", type=int, default=1024)
    parser.add_argument("--generation-seed", type=int, default=21180709)
    parser.add_argument("--selection-seed", type=int, default=21180710)
    parser.add_argument("--topup-size", type=int, default=500)
    parser.add_argument("--max-topup-rounds", type=int, default=10)
    parser.add_argument(
        "--allocated-gpus", default=os.environ.get("CUDA_VISIBLE_DEVICES", "0,1,2,3")
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    root = Path(args.root).resolve()
    gpu_ids = [value.strip() for value in args.allocated_gpus.split(",") if value.strip()]
    if len(gpu_ids) != 4:
        raise SystemExit(f"V5-C calibration generation requires four GPUs, got {gpu_ids}")
    if args.candidate_count != args.per_task * len(TASK_IDS) * 2:
        raise SystemExit("calibration candidate pool must preserve the sealed 2:1 policy")
    if args.candidate_count % len(TASK_IDS):
        raise SystemExit("candidate count must be divisible by four")

    dca_manifest_path = (
        Path(args.checkpoint_manifest).resolve()
        if args.checkpoint_manifest
        else root
        / "checkpoints"
        / args.artifact_scope
        / args.backbone
        / "dca"
        / "round_3"
        / "manifest.json"
    )
    dca_manifest = load_checkpoint_manifest(
        dca_manifest_path,
        role="dca",
        backbone=args.backbone,
        round_index=3,
    )
    output_dir = (
        root
        / "data"
        / args.artifact_scope
        / "v5c_calibration"
        / args.backbone
    )
    output_dir.mkdir(parents=True, exist_ok=True)
    calibration_path = output_dir / "calibration.parquet"
    manifest_path = output_dir / "manifest.json"
    audit_path = output_dir / "selection_audit.json"
    exclusion_path = output_dir / "excluded_fingerprints.json"
    if manifest_path.exists():
        existing = read_json(manifest_path)
        if (
            existing.get("status") == "sealed"
            and existing.get("source_dca_checkpoint_manifest_sha256")
            == sha256_file(dca_manifest_path)
            and existing.get("candidate_count") == args.candidate_count
            and existing.get("per_task") == args.per_task
            and existing.get("generation_seed") == args.generation_seed
            and existing.get("selection_seed") == args.selection_seed
            and calibration_path.exists()
            and existing.get("calibration_sha256") == sha256_file(calibration_path)
        ):
            print(json.dumps(existing, ensure_ascii=False, indent=2), flush=True)
            return
        raise LineageError(f"incompatible existing V5-C calibration output: {output_dir}")

    test_dir = root / "data" / "final_heldout" / args.artifact_scope / args.backbone
    test_path = test_dir / "final_heldout.parquet"
    test_manifest_path = test_dir / "manifest.json"
    exclusion_ledger = build_exclusion_ledger(
        root,
        args.artifact_scope,
        args.backbone,
        [],
    )
    exclusion_ledger = _extend_with_tmcd_test(
        exclusion_ledger,
        test_path=test_path,
        test_manifest_path=test_manifest_path,
    )
    atomic_write_json(exclusion_path, exclusion_ledger)
    excluded_lineage = set(exclusion_ledger["lineage_fingerprints"])
    excluded_semantic = set(exclusion_ledger["semantic_fingerprints"])

    shard_paths = [output_dir / f"candidates.shard_{index}.json" for index in range(4)]
    jobs = []
    for shard_index, (gpu_id, shard_path) in enumerate(zip(gpu_ids, shard_paths)):
        jobs.append(
            (
                _candidate_command(
                    root=root,
                    dca_manifest_path=dca_manifest_path,
                    output=shard_path,
                    num_candidates=args.candidate_count,
                    batch_size=args.batch_size,
                    max_input_tokens=args.max_input_tokens,
                    max_new_tokens=args.max_new_tokens,
                    num_shards=4,
                    shard_index=shard_index,
                    seed=args.generation_seed,
                ),
                _gpu_environment(
                    gpu_id=gpu_id,
                    backbone=args.backbone,
                    namespace=f"shard_{shard_index}",
                ),
            )
        )
    _run_parallel(jobs)

    candidate_path = output_dir / "candidates.json"
    subprocess.run(
        [
            sys.executable,
            str(root / "scripts" / "merge_dca_candidate_shards.py"),
            "--shards",
            *[str(path) for path in shard_paths],
            "--expected-count",
            str(args.candidate_count),
            "--output",
            str(candidate_path),
        ],
        check=True,
    )
    pool = read_json(candidate_path)
    if pool.get("kind") != "dca_candidate_pool":
        raise LineageError("calibration candidates are not a merged DCA pool")
    if int(pool.get("source_dca_round", -1)) != 3:
        raise LineageError("calibration candidates were not generated by DCA_3")
    if pool.get("source_dca_checkpoint_manifest_sha256") != sha256_file(
        dca_manifest_path
    ):
        raise LineageError("calibration candidate checkpoint mismatch")
    candidate_records = list(pool.get("candidates", []) or [])
    initial_task_counts = Counter(
        _task_id(record, scenario)
        if isinstance((scenario := record.get("scenario")), dict)
        else "unknown"
        for record in candidate_records
    )
    expected_initial_task_counts = {
        task_id: args.candidate_count // len(TASK_IDS) for task_id in TASK_IDS
    }
    if dict(initial_task_counts) != expected_initial_task_counts:
        raise LineageError(
            "initial calibration pool is not exactly task-directed: "
            f"{dict(initial_task_counts)} != {expected_initial_task_counts}"
        )

    automatic_topups = []
    for completed_topup_rounds in range(args.max_topup_rounds + 1):
        selected, rejected, eligible_counts = select_heldout(
            candidate_records,
            excluded_lineage,
            excluded_semantic,
            args.per_task,
            args.selection_seed,
            require_quota=False,
        )
        deficient = [task for task in TASK_IDS if eligible_counts[task] < args.per_task]
        if not deficient:
            break
        if completed_topup_rounds == args.max_topup_rounds:
            raise LineageError(
                f"calibration quota remained short after {args.max_topup_rounds} top-ups"
            )
        topup_round = completed_topup_rounds + 1
        topup_jobs = []
        topup_specs = []
        for task_id in deficient:
            task_index = TASK_IDS.index(task_id)
            topup_seed = (
                args.generation_seed
                + topup_round * 100_000_007
                + (task_index + 1) * 1_000_003
            )
            topup_path = output_dir / f"candidates.topup_{task_id}_{topup_round:02d}.json"
            topup_jobs.append(
                (
                    _candidate_command(
                        root=root,
                        dca_manifest_path=dca_manifest_path,
                        output=topup_path,
                        num_candidates=args.topup_size,
                        batch_size=args.batch_size,
                        max_input_tokens=args.max_input_tokens,
                        max_new_tokens=args.max_new_tokens,
                        num_shards=1,
                        shard_index=0,
                        seed=topup_seed,
                        task_id=task_id,
                    ),
                    _gpu_environment(
                        gpu_id=gpu_ids[task_index],
                        backbone=args.backbone,
                        namespace=f"topup_{task_id}_{topup_round:02d}",
                    ),
                )
            )
            topup_specs.append((task_id, topup_seed, topup_path))
        _run_parallel(topup_jobs)
        for task_id, topup_seed, topup_path in topup_specs:
            topup = read_json(topup_path)
            if (
                int(topup.get("source_dca_round", -1)) != 3
                or topup.get("source_dca_checkpoint_manifest_sha256")
                != sha256_file(dca_manifest_path)
                or topup.get("task_id") != task_id
            ):
                raise LineageError(f"invalid calibration top-up: {topup_path}")
            rows = list(topup.get("candidates", []) or [])
            candidate_records.extend(rows)
            automatic_topups.append(
                {
                    "task_id": task_id,
                    "seed": topup_seed,
                    "path": str(topup_path),
                    "sha256": sha256_file(topup_path),
                    "count": len(rows),
                }
            )

    selected, rejected, eligible_counts = select_heldout(
        candidate_records,
        excluded_lineage,
        excluded_semantic,
        args.per_task,
        args.selection_seed,
    )
    rows = []
    for item in selected:
        row = scenario_to_training_row(item["scenario"], split="v5c_calibration")
        extra = dict(row.get("extra_info", {}) or {})
        extra.update(
            {
                "task_id": item["task_id"],
                "scenario_fingerprint": item["scenario_fingerprint"],
                "semantic_overlap_fingerprint": item["semantic_fingerprint"],
                "source_dca_round": 3,
                "source_checkpoint_manifest_sha256": sha256_file(dca_manifest_path),
                "v5c_calibration": True,
                "parameter_training": False,
                "selection_policy": "hard_filter_then_seeded_random",
            }
        )
        row.update(
            {
                "extra_info": extra,
                "task_id": item["task_id"],
                "scenario_fingerprint": item["scenario_fingerprint"],
                "semantic_overlap_fingerprint": item["semantic_fingerprint"],
            }
        )
        rows.append(row)
    pd.DataFrame(rows).to_parquet(calibration_path, index=False)

    selected_lineage = [item["scenario_fingerprint"] for item in selected]
    selected_semantic = [item["semantic_fingerprint"] for item in selected]
    if excluded_lineage.intersection(selected_lineage) or excluded_semantic.intersection(
        selected_semantic
    ):
        raise LineageError("V5-C calibration overlaps formal data or TMCD-Test")
    if len(set(selected_lineage)) != len(selected_lineage) or len(
        set(selected_semantic)
    ) != len(selected_semantic):
        raise LineageError("V5-C calibration contains duplicate scenarios")

    audit = {
        "schema_version": 1,
        "kind": "v5c_calibration_selection_audit",
        "created_at": utc_now(),
        "parameter_training": False,
        "model_performance_filtering": False,
        "frontier_score_filtering": False,
        "oracle_used_for_boolean_solvability_only": True,
        "candidate_count": len(candidate_records),
        "eligible_counts": eligible_counts,
        "rejected_counts": dict(rejected),
        "selected_task_counts": dict(Counter(item["task_id"] for item in selected)),
        "selected_formal_or_test_overlap_count": 0,
        "selected_duplicate_count": 0,
    }
    atomic_write_json(audit_path, audit)
    manifest = {
        "schema_version": 1,
        "kind": "v5c_ecrg_calibration_set",
        "status": "sealed",
        "sealed_at": utc_now(),
        "artifact_scope": args.artifact_scope,
        "backbone": args.backbone,
        "paper_name": "ECRG",
        "code_name": "V5-C",
        "purpose": [
            "hard_admission_thresholds",
            "candidate_ranking_weights",
            "safe_probe_fallback_parameters",
        ],
        "parameter_training": False,
        "tmcd_test_evaluation": False,
        "generation_seed": args.generation_seed,
        "selection_seed": args.selection_seed,
        "selection_policy": "hard_filter_then_seeded_random",
        "model_performance_filtering": False,
        "frontier_score_filtering": False,
        "source_dca_round": 3,
        "source_dca_checkpoint_manifest": str(dca_manifest_path),
        "source_dca_checkpoint_manifest_sha256": sha256_file(dca_manifest_path),
        "source_dca_adapter_sha256": dca_manifest.get("adapter_sha256"),
        "candidate_pool": str(candidate_path),
        "candidate_pool_sha256": sha256_file(candidate_path),
        "candidate_shards": {
            str(index): {"path": str(path), "sha256": sha256_file(path)}
            for index, path in enumerate(shard_paths)
        },
        "initial_candidate_count": args.candidate_count,
        "initial_candidate_task_counts": dict(initial_task_counts),
        "candidate_count": len(candidate_records),
        "candidate_count_per_task": args.candidate_count // len(TASK_IDS),
        "automatic_task_topups": automatic_topups,
        "per_task": args.per_task,
        "selected_count": len(selected),
        "eligible_counts": eligible_counts,
        "task_counts": dict(Counter(item["task_id"] for item in selected)),
        "rejected_counts": dict(rejected),
        "excluded_sealed_tmcd_test": str(test_path.resolve()),
        "excluded_sealed_tmcd_test_sha256": sha256_file(test_path),
        "excluded_sealed_tmcd_test_manifest_sha256": sha256_file(test_manifest_path),
        "exclusion_ledger": str(exclusion_path),
        "exclusion_ledger_sha256": sha256_file(exclusion_path),
        "exclusion_lineage_count": len(excluded_lineage),
        "exclusion_semantic_count": len(excluded_semantic),
        "selected_lineage_fingerprints_sha256": sha256_bytes(
            canonical_json(selected_lineage).encode("utf-8")
        ),
        "selected_semantic_fingerprints_sha256": sha256_bytes(
            canonical_json(selected_semantic).encode("utf-8")
        ),
        "selection_audit": str(audit_path),
        "selection_audit_sha256": sha256_file(audit_path),
        "source_tree_sha256": sha256_source_tree(root / "agentguard_zero"),
        "generator_script_sha256": sha256_file(Path(__file__).resolve()),
        "calibration": str(calibration_path),
        "calibration_sha256": sha256_file(calibration_path),
    }
    atomic_write_json(manifest_path, manifest)
    print(json.dumps(manifest, ensure_ascii=False, indent=2), flush=True)


if __name__ == "__main__":
    main()
