#!/bin/bash
set -euo pipefail

ROOT=${AGZ_ROOT:-/home/share/huadjyin/home/s_qinhua2/AgentGuard-Zero}
source "${ROOT}/scripts/qwen35_env.sh"

BACKBONE=${AGZ_BACKBONE:-qwen3.5-4b}
SOURCE_ROUND=${AGZ_SOURCE_ROUND:-0}
SEED=${AGZ_SEED:-20260709}
PILOT=${AGZ_PILOT:-0}
ALLOCATED_GPUS=${CUDA_VISIBLE_DEVICES:-0,1}

if [[ "${PILOT}" == "1" ]]; then
  ARTIFACT_SCOPE=pilot
  DCA_FEEDBACK_CANDIDATES=${AGZ_DCA_FEEDBACK_CANDIDATES:-8}
  DCA_ROLLOUT_N=${AGZ_DCA_ROLLOUT_N:-2}
  DCA_BATCH_SIZE=${AGZ_DCA_BATCH_SIZE:-4}
  VDA_CANDIDATES=${AGZ_VDA_CANDIDATES:-64}
  VDA_TRAIN_SIZE=${AGZ_VDA_TRAIN_SIZE:-4}
  VDA_DEV_SIZE=${AGZ_VDA_DEV_SIZE:-2}
  VDA_XPLAY_SIZE=${AGZ_VDA_XPLAY_SIZE:-2}
  VDA_BATCH_SIZE=${AGZ_VDA_BATCH_SIZE:-4}
  export AGZ_MAX_RESPONSE_LENGTH=${AGZ_DCA_MAX_RESPONSE_LENGTH:-512}
  export AGZ_MAX_PROMPT_LENGTH=${AGZ_DCA_MAX_PROMPT_LENGTH:-896}
  export AGZ_DCA_REQUIRE_VALID_BATCH=${AGZ_DCA_REQUIRE_VALID_BATCH:-1}
  VDA_MAX_TURNS=${AGZ_VDA_MAX_TURNS:-3}
  export AGZ_VDA_FEEDBACK_MAX_TURNS=${AGZ_VDA_FEEDBACK_MAX_TURNS:-3}
  export AGZ_VDA_FEEDBACK_MAX_INPUT_TOKENS=${AGZ_VDA_FEEDBACK_MAX_INPUT_TOKENS:-2048}
  export AGZ_SAVE_FREQ=${AGZ_SAVE_FREQ:-1}
else
  ARTIFACT_SCOPE=formal
  DCA_FEEDBACK_CANDIDATES=${AGZ_DCA_FEEDBACK_CANDIDATES:-4000}
  DCA_ROLLOUT_N=${AGZ_DCA_ROLLOUT_N:-4}
  DCA_BATCH_SIZE=${AGZ_DCA_BATCH_SIZE:-20}
  VDA_CANDIDATES=${AGZ_VDA_CANDIDATES:-10000}
  VDA_TRAIN_SIZE=${AGZ_VDA_TRAIN_SIZE:-2400}
  VDA_DEV_SIZE=${AGZ_VDA_DEV_SIZE:-400}
  VDA_XPLAY_SIZE=${AGZ_VDA_XPLAY_SIZE:-800}
  VDA_BATCH_SIZE=${AGZ_VDA_BATCH_SIZE:-32}
  export AGZ_MAX_RESPONSE_LENGTH=${AGZ_DCA_MAX_RESPONSE_LENGTH:-512}
  export AGZ_MAX_PROMPT_LENGTH=${AGZ_DCA_MAX_PROMPT_LENGTH:-896}
  export AGZ_DCA_REQUIRE_VALID_BATCH=${AGZ_DCA_REQUIRE_VALID_BATCH:-0}
  VDA_MAX_TURNS=${AGZ_VDA_MAX_TURNS:-16}
  export AGZ_VDA_FEEDBACK_MAX_TURNS=${AGZ_VDA_FEEDBACK_MAX_TURNS:-16}
  export AGZ_VDA_FEEDBACK_MAX_INPUT_TOKENS=${AGZ_VDA_FEEDBACK_MAX_INPUT_TOKENS:-2048}
  # VERL always saves the final step when save_freq is positive. A value above
  # every formal round length avoids bulky intermediate FSDP checkpoints.
  export AGZ_SAVE_FREQ=${AGZ_SAVE_FREQ:-1000000}
fi

if [[ "${BACKBONE}" == "qwen3.5-4b" ]]; then
  if [[ "${PILOT}" != "1" ]]; then
    DCA_BATCH_SIZE=${AGZ_DCA_BATCH_SIZE:-20}
  fi
  CANDIDATE_BATCH_SIZE=${AGZ_CANDIDATE_BATCH_SIZE:-16}
  FEEDBACK_PORT=${AGZ_VDA_FEEDBACK_PORT_A:-31501}
  export AGZ_DCA_PPO_MICRO_BATCH_SIZE_PER_GPU=${AGZ_DCA_PPO_MICRO_BATCH_SIZE_PER_GPU:-4}
  export AGZ_DCA_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU=${AGZ_DCA_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU:-4}
  export AGZ_VDA_PPO_MICRO_BATCH_SIZE_PER_GPU=${AGZ_VDA_PPO_MICRO_BATCH_SIZE_PER_GPU:-1}
  export AGZ_VDA_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU=${AGZ_VDA_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU:-1}
elif [[ "${BACKBONE}" == "qwen3.5-9b" ]]; then
  if [[ "${PILOT}" != "1" ]]; then
    DCA_BATCH_SIZE=${AGZ_DCA_BATCH_SIZE:-20}
  fi
  CANDIDATE_BATCH_SIZE=${AGZ_CANDIDATE_BATCH_SIZE:-8}
  FEEDBACK_PORT=${AGZ_VDA_FEEDBACK_PORT_A:-32501}
  export AGZ_DCA_PPO_MICRO_BATCH_SIZE_PER_GPU=${AGZ_DCA_PPO_MICRO_BATCH_SIZE_PER_GPU:-4}
  export AGZ_DCA_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU=${AGZ_DCA_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU:-4}
  export AGZ_VDA_PPO_MICRO_BATCH_SIZE_PER_GPU=${AGZ_VDA_PPO_MICRO_BATCH_SIZE_PER_GPU:-1}
  export AGZ_VDA_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU=${AGZ_VDA_LOG_PROB_MICRO_BATCH_SIZE_PER_GPU:-1}
else
  echo "Unsupported AGZ_BACKBONE=${BACKBONE}" >&2
  exit 64
fi

mkdir -p "${ROOT}/logs"
echo "Running DCA-first ${BACKBONE} source_round=${SOURCE_ROUND} pilot=${PILOT} on $(hostname)"
echo "Allocated CUDA_VISIBLE_DEVICES=${ALLOCATED_GPUS}"

python -s "${ROOT}/scripts/run_dca_first_round.py" \
  --root "${ROOT}" \
  --backbone "${BACKBONE}" \
  --artifact-scope "${ARTIFACT_SCOPE}" \
  --source-round "${SOURCE_ROUND}" \
  --seed "${SEED}" \
  --allocated-gpus "${ALLOCATED_GPUS}" \
  --dca-feedback-candidates "${DCA_FEEDBACK_CANDIDATES}" \
  --dca-rollout-n "${DCA_ROLLOUT_N}" \
  --dca-batch-size "${DCA_BATCH_SIZE}" \
  --dca-steps "${AGZ_DCA_STEPS:-0}" \
  --vda-candidates "${VDA_CANDIDATES}" \
  --vda-train-size "${VDA_TRAIN_SIZE}" \
  --vda-dev-size "${VDA_DEV_SIZE}" \
  --vda-xplay-size "${VDA_XPLAY_SIZE}" \
  --vda-batch-size "${VDA_BATCH_SIZE}" \
  --vda-rollout-n "${AGZ_VDA_ROLLOUT_N:-1}" \
  --vda-max-turns "${VDA_MAX_TURNS}" \
  --vda-steps "${AGZ_VDA_STEPS:-0}" \
  --candidate-batch-size "${CANDIDATE_BATCH_SIZE}" \
  --feedback-port "${FEEDBACK_PORT}"
